service: nextime-apollo
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  httpApi:
    cors: true
package:
  patterns:
    - src/**
    - '!node_modules/.bin/**'
    - '!node_modules/.pnpm/**'
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-plugin-typescript